[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.4.0"
forge-std = "1.10.0"
solady = "0.1.26"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

remappings = [
    "forge-std-1.10.0/=dependencies/forge-std-1.10.0/",
    "@openzeppelin-contracts-5.4.0/=dependencies/@openzeppelin-contracts-5.4.0/",
    "solady-0.1.26/=dependencies/solady-0.1.26/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
